on:
  release:
    types: [published]
name: Start release process
jobs:
  start_release:
    name: Start ${{ github.event.release.tag_name }}
    runs-on: ubuntu-latest
    environment: publish-artifacts
    steps:
      - name: release ${{ github.event.release.tag_name }}
        run:  echo ${{ github.event.release.prerelease }}
